version: '2'
services:
    postgres:
        image: postgres:9.6-alpine
        environment:
            - "POSTGRES_PASSWORD=${B2SHARE_POSTGRESQL_PASSWORD}"
            - "POSTGRES_USER=${B2SHARE_POSTGRESQL_USER}"
            - "PGDATA=/var/lib/postgresql/data"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:5432:5432"

    elasticsearch:
        build: elasticsearch
        ports:
            - "127.0.0.1:9200:9200"
            - "127.0.0.1:9300:9300"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data

    redis:
        image: redis:3.2-alpine
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - redis-data:/data

    mq:
        hostname: b2share-redis
        image: rabbitmq:3.6-management-alpine
        restart: "always"
        environment:
            - "RABBITMQ_DEFAULT_USER=${B2SHARE_RABBITMQ_USER}"
            - "RABBITMQ_DEFAULT_PASS=${B2SHARE_RABBITMQ_PASS}"
        ports:
            - "127.0.0.1:15672:15672"
            - "127.0.0.1:5672:5672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

volumes:
    postgres-data:
    elasticsearch-data:
    redis-data:
    rabbitmq-data:
